l_project/basic_app/urls.py
from django.conf.urls import url
from basic_app import views
from django.urls import path

app_name = 'basic_app'


urlpatterns=[
    path('',views.index,name='index'),
    path('other/',views.other,name='other'),
    path('relative/',views.relative,name='relative'),
]

l_project/l_project/urls.py
from django.contrib import admin
from django.urls import path,include
from basic_app import views

urlpatterns = [
    #path('',views.index,name="index"),
    path('',include('basic_app.urls')),
    path('admin/', admin.site.urls),

]

l_project/basic_app/models.py
from django.db import models

# Create your models here.

l_project/basic_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def index(request):
    context_dict = {'text':'hello world','number':100}
    return render(request,'basic_app/index.html',context_dict)


def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relative_url_template.html')

l_project/basic_app/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">


  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="navbar-nav">
        <ul class="nav navbar-nav">



          <li><a class="navbar-brand" href="{% url 'basic_app:index' %}">Brand</a></li>
        <li>  <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:other' %}">Other</a></li>

</ul>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      <!-- Anything outside this is inherited -->
      {% endblock %}
    </div>

  </body>
</html>

l_project/basic_app/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <h1>Welcome to index!</h1>
    <h2>This is index.html page showing</h2>
  <h1> {{ text|cut:'hello' }}</h1>
    <h1> {{ number|add:"99" }}</h1>

  {% endblock %}

l_project/basic_app/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
<h1>Welcome to others!</h1>
<h2>This is an example of template inheritance!</h2>
{% endblock %}

l_project/basic_app/templates/basic_app/relative_url_template.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
<h1>Welcome to relative URL templates</h1>
<a href="{% url 'basic_app:other' %}">OTHER PAGE</a>
<br>
<a href="{% url 'admin:index' %}">AdminPage</a>
<br>
<a href="{% url 'basic_app:index' %}">Link to index</a>
  </body>
</html>